#!/bin/sh
#
# script to bring up the tun device in QEMU in bridged mode
#
# $1 is (normally) tap0
#
MYIP=`/sbin/ifconfig eth0| grep "inet addr"| cut -d':' -f2| cut -d' ' -f1`
t="`/sbin/route| grep -n default| cut -d':' -f1`"
MYGATEWAY=`/sbin/route -n| head -${t}| tail -1| awk '{print $2}'`

killall dhclient
/sbin/ifconfig eth0 down
/sbin/ifconfig eth0 0.0.0.0 promisc up

#
# Bring up tap0 with IP 0.0.0.0, create bridge br0 and add interfaces eth0
# and tap0
#
tunctl -t tap0
/sbin/ifconfig $1 0.0.0.0 promisc up
/usr/sbin/brctl addbr br0
/usr/sbin/brctl addif br0 eth0
/usr/sbin/brctl addif br0 $1

#
# Turn spanning tree protocol off
#
/usr/sbin/brctl stp br0 off

#
# Bring up the bridge with our IP and add both default routes
#
/sbin/ifconfig br0 $MYIP up
/sbin/route add default gw $MYGATEWAY

#why /sbin/route add default gw $MYGATEWAY

/etc/init.d/iptables clear
