#!/bin/sh 
# 
# Script to bring down and delete bridge br0 when QEMU exits 
# 

#
# Bring down eth0 and br0 
#
/sbin/ifconfig eth0 down 
/sbin/ifconfig br0 down 

# 
# Delete the bridge
#
/usr/sbin/brctl delbr br0 

# 
# bring up eth0 in "normal" mode 
#
/sbin/ifconfig eth0 -promisc
/sbin/ifconfig eth0 up

tunctl -d tap0
/etc/init.d/network restart
