#!/bin/sh

#
# script to create a list of tarballs for scripts/dl.sh
#
# for developer use only; tarballs/ should already be synced before running
#

HEAD=/lfs/build/JayOS/tarballs
DIRS="jlfs lfs"
XDIRS="xorg/app xorg/driver xorg/font xorg/lib xorg/proto xorg/util xorg/xserver xorg/misc"
PKGLIST=/lfs/build/JayOS/figs/pkglist

# create pkglist in /JayOS/figs
echo "#" > $PKGLIST
echo "# Generated by scripts/dl.sh" >> $PKGLIST
echo "# Used by scripts/create-pkglist.sh" >> $PKGLIST
echo "#" >> $PKGLIST

for i in $DIRS $XDIRS; do
    for j in `ls $HEAD/$i`; do
        echo $i/$j >> $PKGLIST
    done
done
